In [104]:
import numpy as np

In [112]:
arr1 = np.array([1,2,3,4,5])     #1d array

In [3]:
print(arr1)

[1 2 3 4 5]


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
arr1[0:2]

array([1, 2])

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2.ndim

2

In [9]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [10]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

task :  create a 2d numpy array of shape(3,4) with random values

In [11]:
arr1.shape

(5,)

In [12]:
arr2.shape     #rows,columns

(2, 3)

In [13]:
arr3.shape   #matrix,rows,columns

(2, 2, 2)

In [14]:
arr4 = np.array([[[1,2],[3,4],[5,6],[7,8]]])

In [15]:
arr4

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [16]:
arr4.shape

(1, 4, 2)

In [17]:
arr2.size      #total elements

6

In [18]:
arr4.size

8

In [19]:
arr4.dtype

dtype('int32')

In [20]:
my_list = [5,6,7,8,7,8,9,0,19]

In [21]:
my_list

[5, 6, 7, 8, 7, 8, 9, 0, 19]

indexing and slicing

In [22]:
my_list[-1]

19

start:end:stepsize(end pt not included)

In [23]:
my_list[1:8:3]

[6, 7, 0]

2d:row,column

In [24]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr2[1,1]

5

In [26]:
arr2[0,2]

3

In [27]:
arr2[0:,1:]

array([[2, 3],
       [5, 6]])

In [28]:
arr2[1:,0:2]

array([[4, 5]])

3d : matrix,rows,columns

In [29]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [30]:
arr3[0,1,1]

4

In [31]:
arr3[1:,0:,1]

array([[6, 8]])

In [32]:
arr3[0:1,0:,0:1]

array([[[1],
        [3]]])

basic operations

In [33]:
arr1

array([1, 2, 3, 4, 5])

In [34]:
arr1*5

array([ 5, 10, 15, 20, 25])

In [35]:
arr1

array([1, 2, 3, 4, 5])

In [36]:
arr1[arr1>3]

array([4, 5])

In [37]:
arr1.ndim

1

In [38]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])

In [39]:
a+b

array([ 7,  9, 11, 13])

In [40]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [41]:
a*b

array([ 6, 14, 24, 36])

Special arrays

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.random.rand(4,3)

array([[0.42015485, 0.85456334, 0.71097617],
       [0.87560406, 0.30671506, 0.04445595],
       [0.03394991, 0.10065415, 0.28397058],
       [0.6254819 , 0.32799988, 0.06804615]])

In [46]:
arr = np.array([[1,2,3],[4,5,6]])

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr.shape

(2, 3)

In [49]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

task: Convert a 4 * 4 matrix intro a 2 * 8 matrix

In [50]:
b

array([6, 7, 8, 9])

In [51]:
np.sum(b)

30

In [52]:
np.sum(arr1)

15

In [53]:
arr1

array([1, 2, 3, 4, 5])

In [54]:
np.mean(arr1)

3.0

In [55]:
np.max(arr1)

5

task :  find min,max,mean,sum for a random 4 * 4 matrix

In [56]:
np.random.rand(5).astype(int)

array([0, 0, 0, 0, 0])

In [57]:
np.random.randint(2,8)

2

In [58]:
# 0 and 1 in randon.rand

0

In [59]:
np.arange(2,11,2)    

array([ 2,  4,  6,  8, 10])

In [60]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [61]:
np.linspace(1,50,3)         #third parameter is number of elements in the array

array([ 1. , 25.5, 50. ])

In [62]:
np.random.randint(1,100,(3,4))

array([[31,  2, 99, 85],
       [11, 65, 50, 56],
       [54, 76,  7, 82]])

In [63]:
a= np.array([4,2,4,1,6,89,4])

In [64]:
a

array([ 4,  2,  4,  1,  6, 89,  4])

In [65]:
a.sort()

In [66]:
a

array([ 1,  2,  4,  4,  4,  6, 89])

In [67]:
np.where(a%2==0,a/2,a**2)

array([1.000e+00, 1.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 3.000e+00,
       7.921e+03])

view and copy

In [68]:
a

array([ 1,  2,  4,  4,  4,  6, 89])

In [69]:
a= np.array([4,2,4,1,6,89,4])
x = a.copy()
a[0] = 42
print(a)
print(x)

[42  2  4  1  6 89  4]
[ 4  2  4  1  6 89  4]


In [70]:
a= np.array([4,2,4,1,6,89,4]) 
y = a.view()
a[0] = 67
print(a)
print(y)

[67  2  4  1  6 89  4]
[67  2  4  1  6 89  4]


Pandas

In [71]:
!pip install pandas

In [72]:
import pandas as pd

In [73]:
a = [5,6,7,8]

In [74]:
my_series = pd.Series(data = a,index = ['first','second','third','fourth'])

In [75]:
my_series

first     5
second    6
third     7
fourth    8
dtype: int64

In [76]:
type(my_series)

pandas.core.series.Series

In [77]:
my_series['first']

5

In [78]:
arr =np.arange(0,20).reshape(5,4)

In [79]:
df = pd.DataFrame(data=arr,index=['r1','r2','r3','r4','r5'],
                  columns=['c1','c2','c3','c4'])

In [80]:
df

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
r5  16  17  18  19

In [81]:
df.loc['r4','c4']

15

In [82]:
df.iloc[3,3]

15

In [83]:
df.iloc[4,1]

17

loc : index names
    
iloc : index number 

In [84]:
df

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
r5  16  17  18  19

In [85]:
df[df>10]

c1    c2    c3    c4
r1   NaN   NaN   NaN   NaN
r2   NaN   NaN   NaN   NaN
r3   NaN   NaN   NaN  11.0
r4  12.0  13.0  14.0  15.0
r5  16.0  17.0  18.0  19.0

In [86]:
df['c5'] = ['this','is','a','new',np.nan]

In [87]:
df

c1  c2  c3  c4    c5
r1   0   1   2   3  this
r2   4   5   6   7    is
r3   8   9  10  11     a
r4  12  13  14  15   new
r5  16  17  18  19   NaN

In [88]:
df.drop('c5',axis = 1,inplace = True)  

In [89]:
df

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
r5  16  17  18  19

In [90]:
df.drop('r5',axis = 0,inplace = True)

In [91]:
df

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [92]:
df.reset_index(inplace = True)

In [93]:
df

index  c1  c2  c3  c4
0    r1   0   1   2   3
1    r2   4   5   6   7
2    r3   8   9  10  11
3    r4  12  13  14  15

In [94]:
df.set_index('c1')

index  c2  c3  c4
c1                  
0     r1   1   2   3
4     r2   5   6   7
8     r3   9  10  11
12    r4  13  14  15

In [95]:
#del df

In [96]:
df

index  c1  c2  c3  c4
0    r1   0   1   2   3
1    r2   4   5   6   7
2    r3   8   9  10  11
3    r4  12  13  14  15

In [97]:
df.describe()

c1         c2         c3         c4
count   4.000000   4.000000   4.000000   4.000000
mean    6.000000   7.000000   8.000000   9.000000
std     5.163978   5.163978   5.163978   5.163978
min     0.000000   1.000000   2.000000   3.000000
25%     3.000000   4.000000   5.000000   6.000000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   index   4 non-null      object
 1   c1      4 non-null      int32 
 2   c2      4 non-null      int32 
 3   c3      4 non-null      int32 
 4   c4      4 non-null      int32 
dtypes: int32(4), object(1)
memory usage: 224.0+ bytes


In [99]:
df

index  c1  c2  c3  c4
0    r1   0   1   2   3
1    r2   4   5   6   7
2    r3   8   9  10  11
3    r4  12  13  14  15

In [100]:
df.isnull().sum()

index    0
c1       0
c2       0
c3       0
c4       0
dtype: int64

In [101]:
df.nunique()

index    4
c1       4
c2       4
c3       4
c4       4
dtype: int64

In [102]:
df['c2'].unique()

array([ 1,  5,  9, 13])